services:
  api:
    build: .
    ports:
      - "8001:8001"
    network_mode: host
    environment:
      - CUDA_VISIBLE_DEVICES=""
      - CUDA_CACHE_DISABLE=1
    command: granian --interface asgi main:app --host 0.0.0.0 --port 8001
