"""
Script: ingest MLB venues from curated dataset.

Populates the mlb.venues table with all 30 current MLB stadiums
plus alternate names, spring training facilities, and special venues.

The venue_ids are MLB Stats API venue IDs, which are already stored
in mlb.games.venue_id. This script:
  1. Upserts venue records (name, dimensions, capacity, etc.)
  2. Updates surface and roof_type from the venues table back onto
     mlb.games if those fields are missing there.

Idempotent — safe to run multiple times.
"""
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from sqlalchemy import create_engine, text
from app.core.config import settings

sync_url = settings.database_url.replace("+asyncpg", "+psycopg2")
engine = create_engine(sync_url, pool_pre_ping=True)


# ────────────────────────────────────────────────────────────────────
#  Dataset — all MLBsvenue records.
#
#  Sources: MLB.com, Wikipedia "List of current MLB stadiums",
#           ballparksofbaseball.com
#
#  Left_center / right_center are gaps where the exact figure isn't
#  consistently reported; set to approximated midpoint.
# ────────────────────────────────────────────────────────────────────

VENUES = [
    # ── 30 Active MLB Parks ──────────────────────────────────
    {
        "mlb_venue_id": 1,
        "name": "Angel Stadium",
        "city": "Anaheim",
        "state": "CA",
        "capacity": 45517,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 347,
        "left_center": 396,
        "center_field": 396,
        "right_center": 361,
        "right_field": 347,
        "wall_height_left": 18,
        "wall_height_center": 8,
        "wall_height_right": 18,
        "altitude": 160,
        "year_opened": 1966,
        "park_factor_overall": 100.0,
        "park_factor_home_runs": 102.0,
        "description": "Angel Stadium has been the home of the Los Angeles Angels since 1966. Originally a multi-purpose stadium, it was renovated in 1998 to become a baseball-only park with the iconic 'California Spectacular' rock fountain display beyond center field.",
    },
    {
        "mlb_venue_id": 2,
        "name": "Oriole Park at Camden Yards",
        "city": "Baltimore",
        "state": "MD",
        "capacity": 44970,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 333,
        "left_center": 364,
        "center_field": 400,
        "right_center": 373,
        "right_field": 318,
        "wall_height_left": 7,
        "wall_height_center": 7,
        "wall_height_right": 7,
        "altitude": 20,
        "year_opened": 1992,
        "park_factor_overall": 100.0,
        "park_factor_home_runs": 99.0,
        "description": "Camden Yards revolutionized ballpark architecture when it opened in 1992, ushering in the 'retro' era of baseball parks. Its iconic B&O Warehouse beyond right field, brick facade, and intimate design set a new standard for ballpark construction.",
    },
    {
        "mlb_venue_id": 3,
        "name": "Fenway Park",
        "city": "Boston",
        "state": "MA",
        "capacity": 37755,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 310,
        "left_center": 379,
        "center_field": 390,
        "right_center": 420,
        "right_field": 302,
        "wall_height_left": 37,
        "wall_height_center": 3.5,
        "wall_height_right": 3.5,
        "altitude": 20,
        "year_opened": 1912,
        "park_factor_overall": 103.0,
        "park_factor_home_runs": 103.0,
        "description": "Fenway Park is the oldest ballpark in Major League Baseball, having opened in 1912. It's famous for the 37-foot Green Monster in left field, the manually operated scoreboard, the distinctive right-field foul pole known as Pesky's Pole, and its cramped, quirky dimensions that have shaped Red Sox baseball for over a century.",
    },
    {
        "mlb_venue_id": 4,
        "name": "Rate Field",
        "city": "Chicago",
        "state": "IL",
        "capacity": 40615,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 330,
        "left_center": 375,
        "center_field": 400,
        "right_center": 375,
        "right_field": 335,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 596,
        "year_opened": 1991,
        "park_factor_overall": 101.0,
        "park_factor_home_runs": 104.0,
        "description": "Built as a replacement for historic Comiskey Park, Rate Field (formerly Guaranteed Rate Field / U.S. Cellular Field / New Comiskey Park) opened in 1991. It features a distinctive exploding scoreboard and a white sox-shaped shower behind the center field concourse.",
    },
    {
        "mlb_venue_id": 5,
        "name": "Progressive Field",
        "city": "Cleveland",
        "state": "OH",
        "capacity": 34788,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 325,
        "left_center": 370,
        "center_field": 400,
        "right_center": 375,
        "right_field": 325,
        "wall_height_left": 19,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 660,
        "year_opened": 1994,
        "park_factor_overall": 99.0,
        "park_factor_home_runs": 95.0,
        "description": "Progressive Field (formerly Jacobs Field) opened in 1994 alongside the Rock & Roll Hall of Fame. Known for its excellent sightlines and the large LED scoreboard dubbed 'The Hangar' in right-center field. It sparked the renaissance of baseball in Cleveland that included 455 consecutive sellouts from 1995-2001.",
    },
    {
        "mlb_venue_id": 7,
        "name": "Kauffman Stadium",
        "city": "Kansas City",
        "state": "MO",
        "capacity": 37903,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 330,
        "left_center": 387,
        "center_field": 410,
        "right_center": 387,
        "right_field": 330,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 900,
        "year_opened": 1973,
        "park_factor_overall": 97.0,
        "park_factor_home_runs": 88.0,
        "description": "Kauffman Stadium is famous for the spectacular fountains beyond the outfield walls — the largest privately funded fountains in the world. The stadium was extensively renovated in 2009 while preserving its classic crown-shaped facade and symmetrical outfield dimensions. It's named after Ewing Kauffman, the Royals' founding owner.",
    },
    {
        "mlb_venue_id": 10,
        "name": "Oakland Coliseum",
        "city": "Oakland",
        "state": "CA",
        "capacity": 46847,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 330,
        "left_center": 367,
        "center_field": 400,
        "right_center": 367,
        "right_field": 330,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 10,
        "year_opened": 1966,
        "park_factor_overall": 96.0,
        "park_factor_home_runs": 86.0,
        "description": "The Oakland Coliseum was the last remaining multi-purpose stadium in MLB before the Athletics' departure. Notable for Mount Davis — the massive outfield bleachers added when the Raiders returned to Oakland — and its reputation as a pitcher-friendly park with deep power alleys and cool bay air.",
    },
    {
        "mlb_venue_id": 12,
        "name": "Tropicana Field",
        "city": "St. Petersburg",
        "state": "FL",
        "capacity": 25000,
        "surface": "AstroTurf",
        "roof_type": "Closed",
        "left_field": 315,
        "left_center": 370,
        "center_field": 404,
        "right_center": 370,
        "right_field": 322,
        "wall_height_left": 10,
        "wall_height_center": 10,
        "wall_height_right": 10,
        "altitude": 10,
        "year_opened": 1990,
        "park_factor_overall": 95.0,
        "park_factor_home_runs": 92.0,
        "description": "Tropicana Field is MLB's only permanent domed stadium with a non-retractable roof. It features the quirky catwalks suspended from the dome ceiling that occasionally interfere with fly balls. The Trop has hosted the Rays since their inaugural 1998 season. Its capacity has been reduced in recent years with tarped-off upper deck sections.",
    },
    {
        "mlb_venue_id": 14,
        "name": "Rogers Centre",
        "city": "Toronto",
        "state": "ON",
        "capacity": 35395,
        "surface": "AstroTurf",
        "roof_type": "Retractable",
        "left_field": 328,
        "left_center": 375,
        "center_field": 400,
        "right_center": 375,
        "right_field": 328,
        "wall_height_left": 10,
        "wall_height_center": 10,
        "wall_height_right": 10,
        "altitude": 256,
        "year_opened": 1989,
        "park_factor_overall": 102.0,
        "park_factor_home_runs": 104.0,
        "description": "Rogers Centre (originally SkyDome) was the first stadium with a fully retractable roof when it opened in 1989. It's known for the CN Tower backdrop (visible through the glass wall when the roof is open) and the attached hotel with rooms overlooking the field. It hosted the Blue Jays' back-to-back World Series championships in 1992-93. Recent renovations removed the outfield hotel rooms and added a natural grass surface.",
    },
    {
        "mlb_venue_id": 15,
        "name": "Chase Field",
        "city": "Phoenix",
        "state": "AZ",
        "capacity": 48330,
        "surface": "Grass",
        "roof_type": "Retractable",
        "left_field": 330,
        "left_center": 374,
        "center_field": 407,
        "right_center": 374,
        "right_field": 335,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 1100,
        "year_opened": 1998,
        "park_factor_overall": 103.0,
        "park_factor_home_runs": 108.0,
        "description": "Chase Field was the first retractable-roof stadium in the US with a natural grass surface (Tropicana and Rogers Centre preceded it but had artificial turf). The roof usually stays open during the season's early months and closes for the summer heat. Its swimming pool in right-center field is one of baseball's most unique fan experiences.",
    },
    {
        "mlb_venue_id": 17,
        "name": "Wrigley Field",
        "city": "Chicago",
        "state": "IL",
        "capacity": 41649,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 350,
        "left_center": 368,
        "center_field": 400,
        "right_center": 368,
        "right_field": 353,
        "wall_height_left": 11.5,
        "wall_height_center": 6.5,
        "wall_height_right": 6.5,
        "altitude": 600,
        "year_opened": 1914,
        "park_factor_overall": 102.0,
        "park_factor_home_runs": 105.0,
        "description": "Wrigley Field is the second-oldest ballpark in MLB (after Fenway). It's famous for its ivy-covered outfield walls, the hand-operated scoreboard, rooftop bleachers across Waveland and Sheffield Avenues, and being the last ballpark to install lights (1988 — 74 years after opening). Day games still dominate the schedule.",
    },
    {
        "mlb_venue_id": 19,
        "name": "Coors Field",
        "city": "Denver",
        "state": "CO",
        "capacity": 46897,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 347,
        "left_center": 390,
        "center_field": 415,
        "right_center": 375,
        "right_field": 350,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 5200,
        "year_opened": 1995,
        "park_factor_overall": 113.0,
        "park_factor_home_runs": 117.0,
        "description": "Coors Field is famous for its extreme altitude (5,200 feet) that makes it the most hitter-friendly park in MLB. Balls travel up to 10% farther here due to thin air, leading to the 'Coors Effect' — juiced offensive numbers and depressed pitcher stats. The stadium has a distinctive purple row of seats at exactly one mile above sea level.",
    },
    {
        "mlb_venue_id": 22,
        "name": "Dodger Stadium",
        "city": "Los Angeles",
        "state": "CA",
        "capacity": 56000,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 330,
        "left_center": 375,
        "center_field": 400,
        "right_center": 375,
        "right_field": 330,
        "wall_height_left": 10,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 515,
        "year_opened": 1962,
        "park_factor_overall": 97.0,
        "park_factor_home_runs": 93.0,
        "description": "Dodger Stadium is the third-oldest ballpark in MLB and the largest by seating capacity. It's the only stadium from the 1960s still in use that has never undergone a name change or major reconstruction. Known for its stunning views of the San Gabriel Mountains, iconic hexagonal scoreboard, and the famous Dodger Dog.",
    },
    {
        "mlb_venue_id": 31,
        "name": "PNC Park",
        "city": "Pittsburgh",
        "state": "PA",
        "capacity": 38362,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 325,
        "left_center": 383,
        "center_field": 399,
        "right_center": 382,
        "right_field": 320,
        "wall_height_left": 21,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 745,
        "year_opened": 2001,
        "park_factor_overall": 100.0,
        "park_factor_home_runs": 101.0,
        "description": "PNC Park is consistently ranked among the most beautiful ballparks in baseball. Its stunning view of the Pittsburgh skyline and the Roberto Clemente Bridge beyond center field is iconic. The park's intimate design and steep upper deck create excellent sightlines from every seat. It features a 21-foot-high left field wall inspired by Fenway's Green Monster.",
    },
    {
        "mlb_venue_id": 32,
        "name": "American Family Field",
        "city": "Milwaukee",
        "state": "WI",
        "capacity": 41900,
        "surface": "Grass",
        "roof_type": "Retractable",
        "left_field": 342,
        "left_center": 379,
        "center_field": 400,
        "right_center": 374,
        "right_field": 345,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 635,
        "year_opened": 2001,
        "park_factor_overall": 102.0,
        "park_factor_home_runs": 105.0,
        "description": "American Family Field (formerly Miller Park) is known for its distinctive fan-shaped retractable roof — one of the seven-segment panel designs. The roof opens and closes in about 10 minutes, allowing games to be played in any weather. Famous for tailgating culture in its massive parking lots and Bernie Brewer's slide into a mug of foam beer after every home run.",
    },
    {
        "mlb_venue_id": 680,
        "name": "T-Mobile Park",
        "city": "Seattle",
        "state": "WA",
        "capacity": 47929,
        "surface": "Grass",
        "roof_type": "Retractable",
        "left_field": 331,
        "left_center": 378,
        "center_field": 401,
        "right_center": 380,
        "right_field": 326,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 114,
        "year_opened": 1999,
        "park_factor_overall": 97.0,
        "park_factor_home_runs": 91.0,
        "description": "T-Mobile Park (originally Safeco Field) was built to escape the weather challenges of the Kingdome. The retractable roof protects fans from Seattle's rain while still providing an outdoor atmosphere when open. Known for its hitter-unfriendly dimensions, especially the deep right-center power alley that suppresses home runs.",
    },
    {
        "mlb_venue_id": 2392,
        "name": "Daikin Park",
        "city": "Houston",
        "state": "TX",
        "capacity": 41168,
        "surface": "Grass",
        "roof_type": "Retractable",
        "left_field": 315,
        "left_center": 362,
        "center_field": 404,
        "right_center": 373,
        "right_field": 326,
        "wall_height_left": 7,
        "wall_height_center": 7,
        "wall_height_right": 7,
        "altitude": 49,
        "year_opened": 2000,
        "park_factor_overall": 98.0,
        "park_factor_home_runs": 100.0,
        "description": "Daikin Park (formerly Minute Maid Park / Enron Field) features the unique Tal's Hill — a grassy incline in deep center field that was removed in 2017. Its retractable roof is typically closed during Houston's humid summer months. The train on top of the left-field wall that moves after every Astros home run and the flagpole still in play are signature quirks.",
    },
    {
        "mlb_venue_id": 2394,
        "name": "Comerica Park",
        "city": "Detroit",
        "state": "MI",
        "capacity": 41299,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 345,
        "left_center": 370,
        "center_field": 420,
        "right_center": 370,
        "right_field": 330,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 600,
        "year_opened": 2000,
        "park_factor_overall": 101.0,
        "park_factor_home_runs": 104.0,
        "description": "Comerica Park replaced the historic Tiger Stadium in 2000. It features unique brick and steel architecture with a tiger motif throughout, including two massive tiger statues at the main entrance and a carousel. Its deep center field (420 feet) was originally even deeper at 422 feet before the fences were moved in after the 2002 season.",
    },
    {
        "mlb_venue_id": 2395,
        "name": "Oracle Park",
        "city": "San Francisco",
        "state": "CA",
        "capacity": 41915,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 339,
        "left_center": 382,
        "center_field": 391,
        "right_center": 399,
        "right_field": 309,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 20,
        "year_opened": 2000,
        "park_factor_overall": 97.0,
        "park_factor_home_runs": 93.0,
        "description": "Oracle Park (originally Pacific Bell Park / AT&T Park) is renowned for its stunning views of McCovey Cove and the San Francisco Bay beyond right field. It's the only MLB ballpark where fans can watch the game from boats in the water. The right field arcade and 'Splash Hits' that land in the cove are iconic elements. Barry Bonds' 756th and 762nd home run balls landed in McCovey Cove.",
    },
    {
        "mlb_venue_id": 2529,
        "name": "Sutter Health Park",
        "city": "West Sacramento",
        "state": "CA",
        "capacity": 14014,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 330,
        "left_center": 360,
        "center_field": 400,
        "right_center": 360,
        "right_field": 330,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 20,
        "year_opened": 2000,
        "park_factor_overall": 102.0,
        "park_factor_home_runs": 105.0,
        "description": "Sutter Health Park (formerly Raley Field) became the temporary home of the Athletics starting in 2025 while their planned Las Vegas stadium is being built. Originally built as a minor league ballpark for the River Cats (Triple-A affiliate of the Giants), it seats just over 14,000 fans — the smallest capacity in MLB. It faces the Sacramento River with views of the Tower Bridge and downtown Sacramento skyline.",
    },
    {
        "mlb_venue_id": 2602,
        "name": "Great American Ball Park",
        "city": "Cincinnati",
        "state": "OH",
        "capacity": 42319,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 328,
        "left_center": 368,
        "center_field": 404,
        "right_center": 368,
        "right_field": 325,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 490,
        "year_opened": 2003,
        "park_factor_overall": 102.0,
        "park_factor_home_runs": 107.0,
        "description": "Great American Ball Park sits on the banks of the Ohio River, offering views of the riverboat riverfront and the John A. Roebling Suspension Bridge. It features the 'Power Stacks' — four smokestacks that simulate steamboat chimes after every Reds home run — and the 'Moon Deck' beyond center field.",
    },
    {
        "mlb_venue_id": 2680,
        "name": "Petco Park",
        "city": "San Diego",
        "state": "CA",
        "capacity": 40209,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 322,
        "left_center": 370,
        "center_field": 396,
        "right_center": 370,
        "right_field": 322,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 30,
        "year_opened": 2004,
        "park_factor_overall": 94.0,
        "park_factor_home_runs": 85.0,
        "description": "Petco Park is widely regarded as one of baseball's best ballparks. Its Western Metal Supply Company building — an original brick warehouse built in 1911 — is incorporated into the left field corner as part of the stadium structure. The park's spacious dimensions and coastal marine layer air make it one of the most pitcher-friendly parks in MLB.",
    },
    {
        "mlb_venue_id": 2681,
        "name": "Citizens Bank Park",
        "city": "Philadelphia",
        "state": "PA",
        "capacity": 42792,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 329,
        "left_center": 374,
        "center_field": 401,
        "right_center": 369,
        "right_field": 330,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 30,
        "year_opened": 2004,
        "park_factor_overall": 103.0,
        "park_factor_home_runs": 108.0,
        "description": "Citizens Bank Park is known for its hitter-friendly dimensions, passionate fan base, and the iconic Liberty Bell beyond center field that lights up and rings after every Phillies home run. The park features a wide Ashburn Alley concourse that connects the outfield with open views of the field and the Philadelphia skyline.",
    },
    {
        "mlb_venue_id": 2889,
        "name": "Busch Stadium",
        "city": "St. Louis",
        "state": "MO",
        "capacity": 44494,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 336,
        "left_center": 375,
        "center_field": 400,
        "right_center": 375,
        "right_field": 335,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 535,
        "year_opened": 2006,
        "park_factor_overall": 100.0,
        "park_factor_home_runs": 102.0,
        "description": "Busch Stadium is the third ballpark to bear the Busch name, located in downtown St. Louis. It offers an iconic view of the Gateway Arch beyond center field. The stadium is known for its classic red brick exterior and the Cardinals Hall of Fame Museum. Ballpark Village, the entertainment district adjacent to the stadium, has become a major fan destination.",
    },
    {
        "mlb_venue_id": 3289,
        "name": "Citi Field",
        "city": "New York",
        "state": "NY",
        "capacity": 41922,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 335,
        "left_center": 358,
        "center_field": 408,
        "right_center": 378,
        "right_field": 330,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 30,
        "year_opened": 2009,
        "park_factor_overall": 98.0,
        "park_factor_home_runs": 94.0,
        "description": "Citi Field, the home of the New York Mets since 2009, was designed with a nod to Ebbets Field and other classic ballparks. The Jackie Robinson Rotunda at the main entrance honors the Mets legend who broke baseball's color barrier. Its cavernous center field (408 feet) and spacious outfield gaps make it one of the more pitcher-friendly parks in the National League.",
    },
    {
        "mlb_venue_id": 3309,
        "name": "Nationals Park",
        "city": "Washington",
        "state": "DC",
        "capacity": 41339,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 337,
        "left_center": 376,
        "center_field": 402,
        "right_center": 370,
        "right_field": 335,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 30,
        "year_opened": 2008,
        "park_factor_overall": 101.0,
        "park_factor_home_runs": 105.0,
        "description": "Nationals Park was the first LEED-certified 'green' ballpark in the United States. Located in the Navy Yard neighborhood on the Anacostia River, it features a distinctive zinc roof that wraps around the upper deck and a large Washington Monument-inspired scoreboard in center field.",
    },
    {
        "mlb_venue_id": 3312,
        "name": "Target Field",
        "city": "Minneapolis",
        "state": "MN",
        "capacity": 38544,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 328,
        "left_center": 370,
        "center_field": 404,
        "right_center": 370,
        "right_field": 328,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 735,
        "year_opened": 2010,
        "park_factor_overall": 101.0,
        "park_factor_home_runs": 104.0,
        "description": "Target Field finally brought the Twins outdoors after 28 years in the Metrodome. Its limestone and granite exterior is designed to blend with Minnesota's natural landscape. The park offers excellent sightlines and features 'Minneapolis' spelled out in limestone relief above the left field bleachers. Despite Minnesota winters, the field has a sophisticated heating and drainage system that keeps the grass playable from April onward.",
    },
    {
        "mlb_venue_id": 3313,
        "name": "Yankee Stadium",
        "city": "New York",
        "state": "NY",
        "capacity": 46537,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 318,
        "left_center": 385,
        "center_field": 408,
        "right_center": 385,
        "right_field": 314,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 50,
        "year_opened": 2009,
        "park_factor_overall": 103.0,
        "park_factor_home_runs": 111.0,
        "description": "Yankee Stadium replaced the original 'House That Ruth Built' across the street in 2009. The new stadium evokes classic Yankee iconography with its limestone facade, Monument Park in center field, and the frieze that rings the upper deck. Short porches in right (314 feet) and left (318 feet) rank among the shortest dimensions in MLB, making it a premium power hitter's park.",
    },
    {
        "mlb_venue_id": 4169,
        "name": "loanDepot park",
        "city": "Miami",
        "state": "FL",
        "capacity": 36742,
        "surface": "Grass",
        "roof_type": "Retractable",
        "left_field": 335,
        "left_center": 375,
        "center_field": 400,
        "right_center": 378,
        "right_field": 335,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 10,
        "year_opened": 2012,
        "park_factor_overall": 96.0,
        "park_factor_home_runs": 93.0,
        "description": "loanDepot park (originally Marlins Park) is one of MLB's newest ballparks, featuring a retractable roof and air conditioning that keeps the indoor temperature comfortable even during Miami's humid summers. The stadium is known for its colorful contemporary art installations, including the massive home run sculpture in center field, and its blue-green glass exterior that changes color.",
    },
    {
        "mlb_venue_id": 4705,
        "name": "Truist Park",
        "city": "Atlanta",
        "state": "GA",
        "capacity": 41149,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 335,
        "left_center": 370,
        "center_field": 400,
        "right_center": 375,
        "right_field": 325,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 1050,
        "year_opened": 2017,
        "park_factor_overall": 103.0,
        "park_factor_home_runs": 109.0,
        "description": "Truist Park (formerly SunTrust Park) replaced Turner Field for the 2017 season. Part of The Battery Atlanta entertainment complex, the ballpark was designed as the centerpiece of a mixed-use development with restaurants, shops, and hotels. Its higher altitude (1,050 feet) relative to other Southeast parks contributes to above-average home run rates.",
    },
    {
        "mlb_venue_id": 5325,
        "name": "Globe Life Field",
        "city": "Arlington",
        "state": "TX",
        "capacity": 40300,
        "surface": "Grass",
        "roof_type": "Retractable",
        "left_field": 329,
        "left_center": 372,
        "center_field": 407,
        "right_center": 374,
        "right_field": 326,
        "wall_height_left": 8,
        "wall_height_center": 8,
        "wall_height_right": 8,
        "altitude": 550,
        "year_opened": 2020,
        "park_factor_overall": 102.0,
        "park_factor_home_runs": 106.0,
        "description": "Globe Life Field replaced Globe Life Park (the old Rangers stadium) across the street in 2020. The retractable roof was a necessity for Arlington's brutal summer heat. Its distinctive dark gray asymmetrical roof and open left-field concourse that offers views of the old stadium are notable features. The roof's translucent panels allow natural grass to grow even when closed.",
    },
    {
        "mlb_venue_id": 5445,
        "name": "Field of Dreams",
        "city": "Dyersville",
        "state": "IA",
        "capacity": 8000,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 335,
        "left_center": 375,
        "center_field": 400,
        "right_center": 375,
        "right_field": 335,
        "altitude": 800,
        "year_opened": 2021,
        "park_factor_overall": None,
        "park_factor_home_runs": None,
        "description": "A temporary ballpark built adjacent to the original Field of Dreams movie site in Dyersville, Iowa. It has hosted special MLB regular-season games since 2021, including the iconic Field of Dreams game in its inaugural year.",
    },
    # ── Spring Training & Special Venues ─────────────────
    {
        "mlb_venue_id": 2397,
        "name": "Tokyo Dome",
        "city": "Tokyo",
        "state": "",
        "capacity": 45000,
        "surface": "AstroTurf",
        "roof_type": "Closed",
        "year_opened": 1988,
        "description": "The Tokyo Dome, nicknamed 'The Big Egg' for its distinctive domed shape, has hosted MLB regular-season opening series in Japan. It's the home of the Yomiuri Giants of NPB.",
    },
    {
        "mlb_venue_id": 2700,
        "name": "BayCare Ballpark",
        "city": "Clearwater",
        "state": "FL",
        "capacity": 8500,
        "surface": "Grass",
        "roof_type": "Open",
        "year_opened": 2004,
        "description": "Spring training home of the Philadelphia Phillies.",
    },
    {
        "mlb_venue_id": 2523,
        "name": "George M. Steinbrenner Field",
        "city": "Tampa",
        "state": "FL",
        "capacity": 11026,
        "surface": "Grass",
        "roof_type": "Open",
        "year_opened": 1996,
        "description": "Spring training home of the New York Yankees.",
    },
    {
        "mlb_venue_id": 2536,
        "name": "TD Ballpark",
        "city": "Dunedin",
        "state": "FL",
        "capacity": 8500,
        "surface": "Grass",
        "roof_type": "Open",
        "year_opened": 1990,
        "description": "Spring training home of the Toronto Blue Jays.",
    },
    {
        "mlb_venue_id": 2735,
        "name": "Muncy Bank Ballpark",
        "city": "Williamsport",
        "state": "PA",
        "capacity": 1600,
        "surface": "Grass",
        "roof_type": "Open",
        "year_opened": 1926,
        "description": "Home of the Little League World Series. Also known as Journey Bank Ballpark and formerly BB&T Ballpark at Historic Bowman Field. MLB has hosted the 'MLB Little League Classic' here.",
    },
    {
        "mlb_venue_id": 2756,
        "name": "Sahlen Field",
        "city": "Buffalo",
        "state": "NY",
        "capacity": 16100,
        "surface": "Grass",
        "roof_type": "Open",
        "year_opened": 1988,
        "description": "Temporary home of the Toronto Blue Jays during the 2020-21 COVID seasons when Canada-US border restrictions prevented play at Rogers Centre. Normally home to the Buffalo Bisons (Triple-A).",
    },
    {
        "mlb_venue_id": 4162,
        "name": "Jungle Jim's Stadium",
        "city": "Indianapolis",
        "state": "IN",
        "capacity": 14000,
        "surface": "Grass",
        "roof_type": "Open",
        "description": "Also known as Victory Field. Home of the Indianapolis Indians (Triple-A).",
    },
    {
        "mlb_venue_id": 4267,
        "name": "Estadio de Beisbol",
        "city": "Mexico City",
        "state": "",
        "capacity": 20000,
        "surface": "Grass",
        "roof_type": "Open",
        "year_opened": 2019,
        "description": "MLB has hosted regular-season series in Mexico City at this venue (formerly known as Alfredo Harp Helú Stadium).",
    },
    {
        "mlb_venue_id": 4747,
        "name": "Dunkin' Park",
        "city": "Hartford",
        "state": "CT",
        "capacity": 6000,
        "surface": "Grass",
        "roof_type": "Open",
        "year_opened": 2017,
        "description": "Home of the Hartford Yard Goats (Double-A affiliate of the Colorado Rockies).",
    },
    {
        "mlb_venue_id": 4848,
        "name": "Las Vegas Ballpark",
        "city": "Las Vegas",
        "state": "NV",
        "capacity": 10000,
        "surface": "Grass",
        "roof_type": "Open",
        "year_opened": 2019,
        "description": "Home of the Las Vegas Aviators (Triple-A affiliate of the Athletics). The future home of the MLB Athletics once their Las Vegas stadium is built.",
    },
    {
        "mlb_venue_id": 4897,
        "name": "Ballpark of the Palm Beaches",
        "city": "West Palm Beach",
        "state": "FL",
        "capacity": 7700,
        "surface": "Grass",
        "roof_type": "Open",
        "year_opened": 2017,
        "description": "Spring training home shared by the Houston Astros and Washington Nationals.",
    },
    {
        "mlb_venue_id": 5000,
        "name": "CACTI Park of the Palm Beaches",
        "city": "West Palm Beach",
        "state": "FL",
        "capacity": 7700,
        "surface": "Grass",
        "roof_type": "Open",
        "year_opened": 2017,
        "description": "Spring training home of the Houston Astros and Washington Nationals (formerly FITTEAM Ballpark of the Palm Beaches).",
    },
    {
        "mlb_venue_id": 5380,
        "name": "CoolToday Park",
        "city": "North Port",
        "state": "FL",
        "capacity": 8500,
        "surface": "Grass",
        "roof_type": "Open",
        "year_opened": 2019,
        "description": "Spring training home of the Atlanta Braves.",
    },
    # ── Special Event Venues ────────────────────────
    {
        "mlb_venue_id": 3949,
        "name": "Rickwood Field",
        "city": "Birmingham",
        "state": "AL",
        "capacity": 10000,
        "surface": "Grass",
        "roof_type": "Open",
        "left_field": 335,
        "left_center": 370,
        "center_field": 393,
        "right_center": 370,
        "right_field": 325,
        "year_opened": 1910,
        "description": "Rickwood Field is the oldest professional ballpark still in use in the United States, having opened in 1910. It was the home of the Birmingham Barons and the Birmingham Black Barons of the Negro Leagues. MLB hosted a special 'MLB at Rickwood Field' game in 2024 honoring the Negro Leagues, featuring the Cardinals vs the Giants, with Willie Mays celebrated before his passing.",
    },
    {
        "mlb_venue_id": 5150,
        "name": "Gocheok Sky Dome",
        "city": "Seoul",
        "state": "",
        "capacity": 16744,
        "surface": "AstroTurf",
        "roof_type": "Closed",
        "year_opened": 2015,
        "description": "Home of the Kiwoom Heroes of the KBO League. Hosted the MLB World Tour: Seoul Series in 2024, where the Dodgers and Padres opened the regular season in South Korea.",
    },
    {
        "mlb_venue_id": 5340,
        "name": "Estadio Alfredo Harp Helú",
        "city": "Mexico City",
        "state": "",
        "capacity": 20576,
        "surface": "Grass",
        "roof_type": "Open",
        "year_opened": 2019,
        "description": "Home of the Diablos Rojos del México of the Mexican League. MLB has hosted regular-season series here, including the Mexico City Series. The stadium is named after Alfredo Harp Helú, a Mexican businessman and baseball owner. Its high altitude (7,300 feet) creates Coors-like conditions for hitters.",
    },
    {
        "mlb_venue_id": 5355,
        "name": "Las Vegas Ballpark",
        "city": "Las Vegas",
        "state": "NV",
        "capacity": 10000,
        "surface": "Grass",
        "roof_type": "Open",
        "year_opened": 2019,
        "description": "Home of the Las Vegas Aviators (Oakland Athletics Triple-A affiliate). The future site of the MLB Athletics once their Las Vegas stadium is completed.",
    },
    {
        "mlb_venue_id": 5381,
        "name": "London Stadium",
        "city": "London",
        "state": "",
        "capacity": 62500,
        "surface": "Grass",
        "roof_type": "Open",
        "year_opened": 2012,
        "description": "Originally built for the 2012 London Olympics. Converted to a baseball configuration to host the MLB London Series, featuring regular-season games between MLB teams at this iconic venue.",
    },
    {
        "mlb_venue_id": 6130,
        "name": "Bristol Motor Speedway",
        "city": "Bristol",
        "state": "TN",
        "capacity": 72000,
        "surface": "Grass",
        "roof_type": "Open",
        "year_opened": 1961,
        "description": "A NASCAR racetrack that was temporarily converted to host an MLB game between the Atlanta Braves and Cincinnati Reds in August 2025, part of the MLB Speedway Classic. The field was installed in the infield of the stadium, and the configuration created the most unique baseball setting in modern MLB history.",
    },
]


# ────────────────────────────────────────────────────────────────────
#  Ingestion
# ────────────────────────────────────────────────────────────────────

INSERT_SQL = """
INSERT INTO mlb.venues (
    mlb_venue_id, name, city, state, capacity, surface, roof_type,
    left_field, left_center, center_field, right_center, right_field,
    wall_height_left, wall_height_center, wall_height_right,
    altitude, park_factor_overall, park_factor_home_runs,
    description, year_opened
) VALUES (
    :mlb_venue_id, :name, :city, :state, :capacity, :surface, :roof_type,
    :left_field, :left_center, :center_field, :right_center, :right_field,
    :wall_height_left, :wall_height_center, :wall_height_right,
    :altitude, :park_factor_overall, :park_factor_home_runs,
    :description, :year_opened
)
ON CONFLICT (mlb_venue_id)
DO UPDATE SET
    name               = EXCLUDED.name,
    city               = EXCLUDED.city,
    state              = EXCLUDED.state,
    capacity           = EXCLUDED.capacity,
    surface            = EXCLUDED.surface,
    roof_type          = EXCLUDED.roof_type,
    left_field         = EXCLUDED.left_field,
    left_center        = EXCLUDED.left_center,
    center_field       = EXCLUDED.center_field,
    right_center       = EXCLUDED.right_center,
    right_field        = EXCLUDED.right_field,
    wall_height_left   = EXCLUDED.wall_height_left,
    wall_height_center = EXCLUDED.wall_height_center,
    wall_height_right  = EXCLUDED.wall_height_right,
    altitude           = EXCLUDED.altitude,
    park_factor_overall = EXCLUDED.park_factor_overall,
    park_factor_home_runs = EXCLUDED.park_factor_home_runs,
    description        = EXCLUDED.description,
    year_opened        = EXCLUDED.year_opened
"""

UPDATE_GAMES_SQL = """
-- Backfill surface and roof_type on games that are missing them
-- but have a matching venue record.
UPDATE mlb.games g
SET
    surface   = COALESCE(g.surface, v.surface),
    roof_type = COALESCE(g.roof_type, v.roof_type)
FROM mlb.venues v
WHERE v.mlb_venue_id = g.venue_id
  AND (g.surface IS NULL OR g.roof_type IS NULL)
"""


def run():
    print(f"=== MLB Venue Ingestion: {len(VENUES)} records ===")

    with engine.connect() as conn:
        # ── 1. Upsert venues ─────────────────────────
        inserted = 0
        for v in VENUES:
            conn.execute(text(INSERT_SQL), {
                "mlb_venue_id": v["mlb_venue_id"],
                "name": v["name"],
                "city": v["city"],
                "state": v.get("state", ""),
                "capacity": v.get("capacity"),
                "surface": v.get("surface"),
                "roof_type": v.get("roof_type"),
                "left_field": v.get("left_field"),
                "left_center": v.get("left_center"),
                "center_field": v.get("center_field"),
                "right_center": v.get("right_center"),
                "right_field": v.get("right_field"),
                "wall_height_left": v.get("wall_height_left"),
                "wall_height_center": v.get("wall_height_center"),
                "wall_height_right": v.get("wall_height_right"),
                "altitude": v.get("altitude"),
                "park_factor_overall": v.get("park_factor_overall"),
                "park_factor_home_runs": v.get("park_factor_home_runs"),
                "description": v.get("description"),
                "year_opened": v.get("year_opened"),
            })
            inserted += 1

        conn.commit()
        print(f"  ✓ {inserted} venues upserted")

        # ── 2. Backfill games ─────────────────────────
        result = conn.execute(text(UPDATE_GAMES_SQL))
        rows_affected = result.rowcount
        conn.commit()
        if rows_affected:
            print(f"  ✓ {rows_affected} game records updated (surface/roof backfill)")
        else:
            print("  ✓ No games needed backfill")

        # ── 3. Verify ─────────────────────────────────
        row = conn.execute(
            text("SELECT COUNT(*) FROM mlb.venues")
        ).scalar()
        print(f"\n✅ Venue ingestion complete — {row} venues in DB")

    # Validate FK constraint after venues exist
    print("\nValidating FK constraint (games.venue_id → venues.id)...")
    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT COUNT(*) FROM mlb.games g
                WHERE g.venue_id IS NOT NULL
                AND NOT EXISTS (SELECT 1 FROM mlb.venues v WHERE v.mlb_venue_id = g.venue_id)
            """)
        )
        orphan_count = result.scalar()
        if orphan_count:
            print(f"  ⚠ {orphan_count} games have venue_ids without matching venue records")
        else:
            print("  ✓ All game venue_ids have matching venue records")


if __name__ == "__main__":
    run()
