# Complete display_name + description for nfl.features WHERE pick_card=True.
# Keyed by exact feature name (column produced by app/handicapping/nfl/data_loader.py).
# Used by scripts/apply_nfl_pickcard_labels.py

PICKCARD_LABELS = {
    # ================= AWAY STATS =================
    "aimp": ("Away Implied Score", "Away team's implied point total based on the betting line (how many points the market/model expects the away team to score)."),
    "apa": ("Away Points Allowed (PPG)", "Average points the away team's defense gives up per game over the last 5 games."),
    "apf": ("Away Points Scored (PPG)", "Average points the away team's offense scores per game over the last 5 games."),
    "away_ats_away_pct_r5": ("Away ATS% (Road) L5", "Percentage of the away team's last 5 road games that covered the point spread."),
    "away_cold_ppg": ("Away PPG in Cold Games", "Away team's average points scored in prior games played in cold conditions (under 40°F)."),
    "away_cold_win_pct": ("Away Win% in Cold Games", "Away team's win rate in prior games played in cold conditions (under 40°F)."),
    "away_cold_ypg": ("Away YPG in Cold Games", "Away team's average total yards gained in prior games played in cold conditions (under 40°F)."),
    "away_cover_pct_r5": ("Away Cover% L5", "Percentage of the away team's last 5 games that covered the point spread."),
    "away_def_explosive_plays": ("Explosive Plays Against", "How many 20+ yard plays the away defense allowed on average per game (last 5 games)."),
    "away_def_first_downs": ("1st Downs Against", "Average first downs the away defense allowed per game (last 5 games)."),
    "away_def_fourth_down_pct": ("4th Down% Against", "Opponent 4th-down conversion rate against the away defense (last 5 games)."),
    "away_def_ints_thrown": ("INTs Forced (Def)", "Average interceptions the away defense has forced per game (interceptions they've picked off)."),
    "away_def_pass_ypg": ("Away Pass YPG Against", "Average passing yards the away defense allowed per game (last 5 games)."),
    "away_def_passing_rating_rank": ("Def Pass Rating Rank", "Rank of the away defense in opponent passer rating allowed — lower is better league-wide."),
    "away_def_rush_ypg": ("Away Rush YPG Against", "Average rushing yards the away defense allowed per game (last 5 games)."),
    "away_def_rushing_rank": ("Def Rush Yards Rank", "Rank of the away defense in rushing yards allowed — lower is better league-wide."),
    "away_def_rz_td_pct": ("RZ TD% Against", "Opponent red-zone touchdown percentage against the away defense — how often opponents score TDs once inside the 20-yard line."),
    "away_def_rz_trips": ("RZ Trips Against", "Average red-zone trips the away defense allowed — how often opponents reached the red zone (last 5 games)."),
    "away_def_scoring_rank": ("Def Scoring Rank", "Rank of the away defense in points allowed — lower is better league-wide."),
    "away_def_third_down_pct": ("3rd Down% Against", "Opponent 3rd-down conversion rate against the away defense (last 5 games)."),
    "away_def_three_and_outs": ("3&Outs Forced (Def)", "Average three-and-outs the away defense forced per game (last 5 games)."),
    "away_def_yardage_rank": ("Def Yardage Rank", "Rank of the away defense in total yards allowed — lower is better league-wide."),
    "away_def_ypg": ("Away Total YPG Against", "Average total (passing + rushing) yards the away defense allowed per game (last 5 games)."),
    "away_def_ypp": ("Away Yards/Play Against", "Average yards the away defense allowed per play — a measure of defensive efficiency (last 5 games)."),
    "away_embarrassed": ("Away Embarrassed (Lost 14+)", "Flag: 1 if the away team lost its last game by 14 or more points, otherwise 0."),
    "away_explosive_plays": ("Away Explosive Plays", "Average 20+ yard plays the away offense produced per game (last 5 games)."),
    "away_first_downs": ("Away 1st Downs", "Average first downs the away offense earned per game (last 5 games)."),
    "away_fourth_down_pct": ("Away 4th Down%", "Away team's 4th-down conversion percentage (last 5 games)."),
    "away_ints_thrown": ("Away INTs Thrown", "Average interceptions the away offense threw per game (last 5 games)."),
    "away_margin_r10": ("Away Margin L10", "Away team's average point differential over the last 10 games (positive = outscoring opponents)."),
    "away_margin_r3": ("Away Margin L3", "Away team's average point differential over the last 3 games (positive = outscoring opponents)."),
    "away_off_passing_rank": ("Off Pass Yards Rank", "Rank of the away offense in passing yards — higher is better league-wide."),
    "away_off_rushing_rank": ("Off Rush Yards Rank", "Rank of the away offense in rushing yards — higher is better league-wide."),
    "away_off_scoring_rank": ("Off Scoring Rank", "Rank of the away offense in points scored — higher is better league-wide."),
    "away_off_yardage_rank": ("Off Yardage Rank", "Rank of the away offense in total yards gained — higher is better league-wide."),
    "away_off_ypg": ("Away Total YPG", "Average total (passing + rushing) yards the away offense gained per game (last 5 games)."),
    "away_ou_margin_r5": ("Away OU Margin L5", "Average difference between the actual total points scored and the closing over/under line in the away team's last 5 games (positive = games went over)."),
    "away_ou_over_pct_r5": ("Away Over% L5", "Percentage of the away team's last 5 games that went over the closing over/under total."),
    "away_pass_ypa": ("Away Pass YPA", "Away team's average passing yards per pass attempt (last 5 games)."),
    "away_pass_ypg": ("Away Pass YPG", "Average passing yards the away offense gained per game (last 5 games)."),
    "away_precip_ppg": ("Away PPG in Rain/Snow", "Away team's average points scored in prior games played in precipitation (rain or snow)."),
    "away_precip_win_pct": ("Away Win% in Rain/Snow", "Away team's win rate in prior games played in precipitation (rain or snow)."),
    "away_precip_ypg": ("Away YPG in Rain/Snow", "Away team's average total yards gained in prior games played in precipitation (rain or snow)."),
    "away_qb_any_a_5": ("Away QB ANY/A L5", "Away QB's adjusted net yards per pass attempt over the last 5 games (accounts for sacks, INTs, and TDs)."),
    "away_qb_any_a_season": ("Away QB ANY/A Season", "Away QB's adjusted net yards per pass attempt this season (accounts for sacks, INTs, and TDs)."),
    "away_qb_cold_passer_rating": ("Away QB Rating in Cold", "Away QB's passer rating in prior starts played in cold conditions (under 40°F)."),
    "away_qb_cold_starts": ("Away QB Cold Starts", "Number of the away QB's prior career starts in cold conditions (under 40°F) — a measure of cold-weather experience."),
    "away_qb_cold_warm_passer_rating": ("Away QB Weather-Aware Rating", "Away QB's weather-adjusted passer rating — uses cold-game rating when under 40°F, otherwise warm-game rating."),
    "away_qb_games_5": ("Away QB Games L5", "Number of games the away QB played in the last 5 team games — an availability/reliability check."),
    "away_qb_games_season": ("Away QB Games Season", "Number of games the away QB has played this season — a measure of experience."),
    "away_qb_int_pct_5": ("Away QB INT% L5", "Away QB's interception percentage (INTs per pass attempt) over the last 5 games."),
    "away_qb_int_pct_season": ("Away QB INT% Season", "Away QB's interception percentage (INTs per pass attempt) this season."),
    "away_qb_passer_rating_5": ("Away QB Rating L5", "Away QB's passer rating over the last 5 games."),
    "away_qb_passer_rating_season": ("Away QB Rating Season", "Away QB's passer rating this season."),
    "away_qb_passer_rating_trend": ("Away QB Rating Trend", "Away QB's recent passer rating minus their season average — positive means playing above their season norm (hot streak)."),
    "away_qb_precip_passer_rating": ("Away QB Rating in Rain/Snow", "Away QB's passer rating in prior starts played in precipitation (rain or snow)."),
    "away_qb_precip_starts": ("Away QB Rain/Snow Starts", "Number of the away QB's prior starts in precipitation (rain or snow) — a measure of weather experience."),
    "away_qb_rush_att_5": ("Away QB Rush Att L5", "Total rush attempts by the away QB over the last 5 games."),
    "away_qb_rush_att_pg_season": ("Away QB Rush Att/Game Season", "Away QB's rush attempts per game this season."),
    "away_qb_rush_ypg_5": ("Away QB Rush YPG L5", "Away QB's rushing yards per game over the last 5 games."),
    "away_qb_rush_ypg_season": ("Away QB Rush YPG Season", "Away QB's rushing yards per game this season."),
    "away_qb_sack_rate_5": ("Away QB Sack% L5", "Away QB's sack rate (sacks per dropback) over the last 5 games."),
    "away_qb_sack_rate_season": ("Away QB Sack% Season", "Away QB's sack rate (sacks per dropback) this season."),
    "away_qb_td_pct_5": ("Away QB TD% L5", "Away QB's touchdown percentage (TDs per pass attempt) over the last 5 games."),
    "away_qb_td_pct_season": ("Away QB TD% Season", "Away QB's touchdown percentage (TDs per pass attempt) this season."),
    "away_qb_ypa_5": ("Away QB YPA L5", "Away QB's yards per pass attempt over the last 5 games."),
    "away_qb_ypa_season": ("Away QB YPA Season", "Away QB's yards per pass attempt this season."),
    "away_qb_ypa_trend": ("Away QB YPA Trend", "Away QB's recent yards per attempt minus their season average — positive means passing above their season norm."),
    "away_rush_ypa": ("Away Rush YPA", "Away team's average rushing yards per carry (last 5 games)."),
    "away_rush_ypg": ("Away Rush YPG", "Average rushing yards the away offense gained per game (last 5 games)."),
    "away_turnover_diff_r5": ("Away Turnover Diff L5", "Away team's turnover differential over the last 5 games (positive = forcing more turnovers than committing)."),
    "away_win_pct_r5": ("Away Win% L5", "Away team's win percentage over the last 5 games."),
    "away_win_streak": ("Away Win Streak", "Away team's current win streak (negative number = current losing streak)."),
    "away_weighted_margin_r5": ("Away Weighted Margin L5", "Away team's average point differential over the last 5 games with more recent games weighted higher."),
    "away_ypp": ("Away Yards/Play", "Average yards the away offense gained per play — the best single measure of offensive efficiency (last 5 games)."),
    "away_rz_td_pct": ("Away RZ TD%", "Away team's red-zone touchdown percentage — how often the away offense converts trips inside the 20-yard line into touchdowns."),
    "away_rz_trips": ("Away RZ Trips", "Average number of times per game the away offense reached the red zone (inside the 20-yard line)."),
    "away_third_down_pct": ("Away 3rd Down%", "Away team's 3rd-down conversion percentage — how often the away offense moves the chains on 3rd down."),
    "away_three_and_outs": ("Away 3&Outs", "Average three-and-outs by the away offense per game — drives where they gained under 10 yards and had to punt."),
    "away_team_cold_warm_ppg": ("Away PPG (Weather-Adjusted)", "Away team's points-per-game using their cold-weather rating if under 40°F, otherwise their warm-weather rating."),
    "away_team_cold_warm_ypg": ("Away YPG (Weather-Adjusted)", "Away team's yards-per-game using their cold-weather rating if under 40°F, otherwise their warm-weather rating."),
    "away_team_cold_warm_win_pct": ("Away Win% (Weather-Adjusted)", "Away team's win percentage using their cold-weather rating if under 40°F, otherwise their warm-weather rating."),
    "away_team_precip_dry_ppg": ("Away PPG (Weather-Adjusted)", "Away team's points-per-game using their rain/snow rating if it's precipitating, otherwise their dry-weather rating."),
    "away_team_precip_dry_ypg": ("Away YPG (Weather-Adjusted)", "Away team's yards-per-game using their rain/snow rating if it's precipitating, otherwise their dry-weather rating."),
    "away_team_precip_dry_win_pct": ("Away Win% (Weather-Adjusted)", "Away team's win percentage using their rain/snow rating if it's precipitating, otherwise their dry-weather rating."),
    "away_qb_precip_dry_passer_rating": ("Away QB Rating (Precip-Adjusted)", "Away QB's passer rating using their rain/snow rating if it's precipitating, otherwise their dry-weather rating."),

    # ================= HOME STATS =================
    "himp": ("Home Implied Score", "Home team's implied point total based on the betting line (how many points the market/model expects the home team to score)."),
    "hpa": ("Home Points Allowed (PPG)", "Average points the home team's defense gives up per game over the last 5 games."),
    "hpf": ("Home Points Scored (PPG)", "Average points the home team's offense scores per game over the last 5 games."),
    "home_ats_home_pct_r5": ("Home ATS% (Home) L5", "Percentage of the home team's last 5 home games that covered the point spread."),
    "home_cold_ppg": ("Home PPG in Cold Games", "Home team's average points scored in prior games played in cold conditions (under 40°F)."),
    "home_cold_win_pct": ("Home Win% in Cold Games", "Home team's win rate in prior games played in cold conditions (under 40°F)."),
    "home_cold_ypg": ("Home YPG in Cold Games", "Home team's average total yards gained in prior games played in cold conditions (under 40°F)."),
    "home_cover_pct_r5": ("Home Cover% L5", "Percentage of the home team's last 5 games that covered the point spread."),
    "home_def_explosive_plays": ("Explosive Plays Against", "How many 20+ yard plays the home defense allowed on average per game (last 5 games)."),
    "home_def_first_downs": ("1st Downs Against", "Average first downs the home defense allowed per game (last 5 games)."),
    "home_def_fourth_down_pct": ("4th Down% Against", "Opponent 4th-down conversion rate against the home defense (last 5 games)."),
    "home_def_ints_thrown": ("INTs Forced (Def)", "Average interceptions the home defense has forced per game (interceptions they've picked off)."),
    "home_def_pass_ypg": ("Home Pass YPG Against", "Average passing yards the home defense allowed per game (last 5 games)."),
    "home_def_passing_rating_rank": ("Def Pass Rating Rank", "Rank of the home defense in opponent passer rating allowed — lower is better league-wide."),
    "home_def_rush_ypg": ("Home Rush YPG Against", "Average rushing yards the home defense allowed per game (last 5 games)."),
    "home_def_rushing_rank": ("Def Rush Yards Rank", "Rank of the home defense in rushing yards allowed — lower is better league-wide."),
    "home_def_rz_td_pct": ("RZ TD% Against", "Opponent red-zone touchdown percentage against the home defense — how often opponents score TDs once inside the 20-yard line."),
    "home_def_rz_trips": ("RZ Trips Against", "Average red-zone trips the home defense allowed — how often opponents reached the red zone (last 5 games)."),
    "home_def_scoring_rank": ("Def Scoring Rank", "Rank of the home defense in points allowed — lower is better league-wide."),
    "home_def_third_down_pct": ("3rd Down% Against", "Opponent 3rd-down conversion rate against the home defense (last 5 games)."),
    "home_def_three_and_outs": ("3&Outs Forced (Def)", "Average three-and-outs the home defense forced per game (last 5 games)."),
    "home_def_yardage_rank": ("Def Yardage Rank", "Rank of the home defense in total yards allowed — lower is better league-wide."),
    "home_def_ypg": ("Home Total YPG Against", "Average total (passing + rushing) yards the home defense allowed per game (last 5 games)."),
    "home_def_ypp": ("Home Yards/Play Against", "Average yards the home defense allowed per play — a measure of defensive efficiency (last 5 games)."),
    "home_embarrassed": ("Home Embarrassed (Lost 14+)", "Flag: 1 if the home team lost its last game by 14 or more points, otherwise 0."),
    "home_explosive_plays": ("Home Explosive Plays", "Average 20+ yard plays the home offense produced per game (last 5 games)."),
    "home_first_downs": ("Home 1st Downs", "Average first downs the home offense earned per game (last 5 games)."),
    "home_fourth_down_pct": ("Home 4th Down%", "Home team's 4th-down conversion percentage (last 5 games)."),
    "home_ints_thrown": ("Home INTs Thrown", "Average interceptions the home offense threw per game (last 5 games)."),
    "home_margin_r10": ("Home Margin L10", "Home team's average point differential over the last 10 games (positive = outscoring opponents)."),
    "home_margin_r3": ("Home Margin L3", "Home team's average point differential over the last 3 games (positive = outscoring opponents)."),
    "home_off_passing_rank": ("Off Pass Yards Rank", "Rank of the home offense in passing yards — higher is better league-wide."),
    "home_off_rushing_rank": ("Off Rush Yards Rank", "Rank of the home offense in rushing yards — higher is better league-wide."),
    "home_off_scoring_rank": ("Off Scoring Rank", "Rank of the home offense in points scored — higher is better league-wide."),
    "home_off_yardage_rank": ("Off Yardage Rank", "Rank of the home offense in total yards gained — higher is better league-wide."),
    "home_off_ypg": ("Home Total YPG", "Average total (passing + rushing) yards the home offense gained per game (last 5 games)."),
    "home_ou_margin_r5": ("Home OU Margin L5", "Average difference between the actual total points scored and the closing over/under line in the home team's last 5 games (positive = games went over)."),
    "home_ou_over_pct_r5": ("Home Over% L5", "Percentage of the home team's last 5 games that went over the closing over/under total."),
    "home_pass_ypa": ("Home Pass YPA", "Home team's average passing yards per pass attempt (last 5 games)."),
    "home_pass_ypg": ("Home Pass YPG", "Average passing yards the home offense gained per game (last 5 games)."),
    "home_precip_ppg": ("Home PPG in Rain/Snow", "Home team's average points scored in prior games played in precipitation (rain or snow)."),
    "home_precip_win_pct": ("Home Win% in Rain/Snow", "Home team's win rate in prior games played in precipitation (rain or snow)."),
    "home_precip_ypg": ("Home YPG in Rain/Snow", "Home team's average total yards gained in prior games played in precipitation (rain or snow)."),
    "home_qb_any_a_5": ("Home QB ANY/A L5", "Home QB's adjusted net yards per pass attempt over the last 5 games (accounts for sacks, INTs, and TDs)."),
    "home_qb_any_a_season": ("Home QB ANY/A Season", "Home QB's adjusted net yards per pass attempt this season (accounts for sacks, INTs, and TDs)."),
    "home_qb_cold_passer_rating": ("Home QB Rating in Cold", "Home QB's passer rating in prior starts played in cold conditions (under 40°F)."),
    "home_qb_cold_starts": ("Home QB Cold Starts", "Number of the home QB's prior career starts in cold conditions (under 40°F) — a measure of cold-weather experience."),
    "home_qb_cold_warm_passer_rating": ("Home QB Weather-Aware Rating", "Home QB's weather-adjusted passer rating — uses cold-game rating when under 40°F, otherwise warm-game rating."),
    "home_qb_games_5": ("Home QB Games L5", "Number of games the home QB played in the last 5 team games — an availability/reliability check."),
    "home_qb_games_season": ("Home QB Games Season", "Number of games the home QB has played this season — a measure of experience."),
    "home_qb_int_pct_5": ("Home QB INT% L5", "Home QB's interception percentage (INTs per pass attempt) over the last 5 games."),
    "home_qb_int_pct_season": ("Home QB INT% Season", "Home QB's interception percentage (INTs per pass attempt) this season."),
    "home_qb_passer_rating_5": ("Home QB Rating L5", "Home QB's passer rating over the last 5 games."),
    "home_qb_passer_rating_season": ("Home QB Rating Season", "Home QB's passer rating this season."),
    "home_qb_passer_rating_trend": ("Home QB Rating Trend", "Home QB's recent passer rating minus their season average — positive means playing above their season norm (hot streak)."),
    "home_qb_precip_passer_rating": ("Home QB Rating in Rain/Snow", "Home QB's passer rating in prior starts played in precipitation (rain or snow)."),
    "home_qb_precip_starts": ("Home QB Rain/Snow Starts", "Number of the home QB's prior starts in precipitation (rain or snow) — a measure of weather experience."),
    "home_qb_rush_att_5": ("Home QB Rush Att L5", "Total rush attempts by the home QB over the last 5 games."),
    "home_qb_rush_att_pg_season": ("Home QB Rush Att/Game Season", "Home QB's rush attempts per game this season."),
    "home_qb_rush_ypg_5": ("Home QB Rush YPG L5", "Home QB's rushing yards per game over the last 5 games."),
    "home_qb_rush_ypg_season": ("Home QB Rush YPG Season", "Home QB's rushing yards per game this season."),
    "home_qb_sack_rate_5": ("Home QB Sack% L5", "Home QB's sack rate (sacks per dropback) over the last 5 games."),
    "home_qb_sack_rate_season": ("Home QB Sack% Season", "Home QB's sack rate (sacks per dropback) this season."),
    "home_qb_td_pct_5": ("Home QB TD% L5", "Home QB's touchdown percentage (TDs per pass attempt) over the last 5 games."),
    "home_qb_td_pct_season": ("Home QB TD% Season", "Home QB's touchdown percentage (TDs per pass attempt) this season."),
    "home_qb_ypa_5": ("Home QB YPA L5", "Home QB's yards per pass attempt over the last 5 games."),
    "home_qb_ypa_season": ("Home QB YPA Season", "Home QB's yards per pass attempt this season."),
    "home_qb_ypa_trend": ("Home QB YPA Trend", "Home QB's recent yards per attempt minus their season average — positive means passing above their season norm."),
    "home_rush_ypa": ("Home Rush YPA", "Home team's average rushing yards per carry (last 5 games)."),
    "home_rush_ypg": ("Home Rush YPG", "Average rushing yards the home offense gained per game (last 5 games)."),
    "home_turnover_diff_r5": ("Home Turnover Diff L5", "Home team's turnover differential over the last 5 games (positive = forcing more turnovers than committing)."),
    "home_win_pct_r5": ("Home Win% L5", "Home team's win percentage over the last 5 games."),
    "home_win_streak": ("Home Win Streak", "Home team's current win streak (negative number = current losing streak)."),
    "home_weighted_margin_r5": ("Home Weighted Margin L5", "Home team's average point differential over the last 5 games with more recent games weighted higher."),
    "home_ypp": ("Home Yards/Play", "Average yards the home offense gained per play — the best single measure of offensive efficiency (last 5 games)."),
    "home_rz_td_pct": ("Home RZ TD%", "Home team's red-zone touchdown percentage — how often the home offense converts trips inside the 20-yard line into touchdowns."),
    "home_rz_trips": ("Home RZ Trips", "Average number of times per game the home offense reached the red zone (inside the 20-yard line)."),
    "home_third_down_pct": ("Home 3rd Down%", "Home team's 3rd-down conversion percentage — how often the home offense moves the chains on 3rd down."),
    "home_three_and_outs": ("Home 3&Outs", "Average three-and-outs by the home offense per game — drives where they gained under 10 yards and had to punt."),
    "home_team_cold_warm_ppg": ("Home PPG (Weather-Adjusted)", "Home team's points-per-game using their cold-weather rating if under 40°F, otherwise their warm-weather rating."),
    "home_team_cold_warm_ypg": ("Home YPG (Weather-Adjusted)", "Home team's yards-per-game using their cold-weather rating if under 40°F, otherwise their warm-weather rating."),
    "home_team_cold_warm_win_pct": ("Home Win% (Weather-Adjusted)", "Home team's win percentage using their cold-weather rating if under 40°F, otherwise their warm-weather rating."),
    "home_team_precip_dry_ppg": ("Home PPG (Weather-Adjusted)", "Home team's points-per-game using their rain/snow rating if it's precipitating, otherwise their dry-weather rating."),
    "home_team_precip_dry_ypg": ("Home YPG (Weather-Adjusted)", "Home team's yards-per-game using their rain/snow rating if it's precipitating, otherwise their dry-weather rating."),
    "home_team_precip_dry_win_pct": ("Home Win% (Weather-Adjusted)", "Home team's win percentage using their rain/snow rating if it's precipitating, otherwise their dry-weather rating."),
    "home_qb_precip_dry_passer_rating": ("Home QB Rating (Precip-Adjusted)", "Home QB's passer rating using their rain/snow rating if it's precipitating, otherwise their dry-weather rating."),

    # ================= BETTING LINES =================
    "opening_ou": ("Opening OU Line", "The over/under total when the betting line first opened for this game."),
    "ou_movement": ("OU Movement", "How much the over/under total moved from opening to the closing line (closing minus opening; positive = line went up)."),
    "sp_a_odds_mvmt": ("Away Spread Odds Move", "Movement in the away team's spread odds (juice) from opening to closing — shows where the money is going."),
    "sp_h_odds_mvmt": ("Home Spread Odds Move", "Movement in the home team's spread odds (juice) from opening to closing — shows where the money is going."),
    "spread": ("Closing Spread", "The closing point spread — number of points the home team is favored (negative = home favored; positive = away favored)."),
    "spread_movement": ("Spread Movement", "How much the point spread moved from opening to the closing line (closing minus opening)."),
    "away_season_ats_pct": ("Away Season ATS%", "Percentage of the away team's games this season that covered the point spread."),
    "home_season_ats_pct": ("Home Season ATS%", "Percentage of the home team's games this season that covered the point spread."),

    # ================= GAME CONTEXT =================
    "is_division_game": ("Division Game", "Flag: 1 if this is a division matchup (both teams in the same division) — division games tend to be closer, 0 otherwise."),
    "is_dome": ("Dome Game", "Flag: 1 if the game is played in a domed or retractable-roof stadium — weather has less impact on play."),
    "venue_elevation_ft": ("Elevation (ft)", "Stadium elevation above sea level in feet — matters at high-altitude venues like Denver, can affect passing/kicking."),
    "is_primetime": ("Primetime Game", "Flag: 1 if the game is in primetime (Sunday/Monday/Thursday night), 0 otherwise."),
    "qb_any_a_5_diff": ("QB ANY/A Diff L5", "Difference in QB efficiency between the two teams (home minus away) using last-5-game ANY/A — positive favors the home QB."),
    "qb_any_a_season_diff": ("QB ANY/A Diff Season", "Difference in QB efficiency between the two teams (home minus away) using season ANY/A — positive favors the home QB."),
    "qb_passer_rating_5_diff": ("QB Rating Diff L5", "Difference in QB passer rating between the two teams (home minus away) over the last 5 games — positive favors the home QB."),
    "qb_passer_rating_season_diff": ("QB Rating Diff Season", "Difference in QB passer rating between the two teams (home minus away) this season — positive favors the home QB."),
    "rest_diff": ("Rest Advantage (Days)", "Rest-day differential — home team's rest days minus away team's rest days. Positive means the home team is better rested."),
    "season_avg_pts": ("League Avg Points", "Average points scored per team per game across the entire league this season — context for judging totals."),
    "is_short": ("Short Week", "Flag: 1 if the away team is playing on a short week (fewer than normal rest days), 0 otherwise."),
    "temp": ("Temperature (°F)", "Expected game-time temperature in degrees Fahrenheit at the stadium."),
    "travel_miles": ("Travel Distance (mi)", "Distance in miles the away team travels to reach the game — long travel can affect performance."),
    "tz_diff": ("Timezone Difference (hrs)", "Timezone difference between the two teams' home cities in hours — a jet-lag / travel adjustment factor."),
    "wind": ("Wind Speed (mph)", "Expected game-time wind speed in miles per hour at the stadium — high wind affects passing and kicking."),
}
