// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[sport]" | "/[sport]/games/[id]" | "/[sport]/players" | "/[sport]/players/[id]" | "/[sport]/schedule" | "/[sport]/stats" | "/[sport]/teams" | "/[sport]/teams/[abbreviation]" | "/admin" | "/admin/articles" | "/admin/articles/rss" | "/admin/models" | "/admin/plans" | "/admin/predictions" | "/admin/subscriptions" | "/admin/users" | "/chat" | "/games" | "/login" | "/players" | "/players/[id]" | "/register" | "/stats" | "/teams" | "/teams/[abbreviation]"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]" | "/auth/[[...path]]" | "/health"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/[sport]": { "sport": string; }
  "/[sport]/games/[id]": { "sport": string; "id": string; }
  "/[sport]/players": { "sport": string; }
  "/[sport]/players/[id]": { "sport": string; "id": string; }
  "/[sport]/schedule": { "sport": string; }
  "/[sport]/stats": { "sport": string; }
  "/[sport]/teams": { "sport": string; }
  "/[sport]/teams/[abbreviation]": { "sport": string; "abbreviation": string; }
  "/admin": {}
  "/admin/articles": {}
  "/admin/articles/rss": {}
  "/admin/models": {}
  "/admin/plans": {}
  "/admin/predictions": {}
  "/admin/subscriptions": {}
  "/admin/users": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/auth/[[...path]]": { "path"?: string[]; }
  "/chat": {}
  "/games": {}
  "/health": {}
  "/login": {}
  "/players": {}
  "/players/[id]": { "id": string; }
  "/register": {}
  "/stats": {}
  "/teams": {}
  "/teams/[abbreviation]": { "abbreviation": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
