// rss.ts — minimal RSS 2.0 builder for Earl Knows Ball content feeds.
//
// Feeds are generated by Next.js route handlers under src/app/**/feed.xml,
// which fetch item data from the backend `/seo/feed-data` endpoint and render
// RSS here. Keeping the XML assembly in one place keeps escaping correct and
// the two feeds (articles+recaps, game previews) consistent.

export const SITE_URL = "https://earlknowsball.com";

export type FeedItem = {
  title: string;
  /** Absolute canonical URL of the item. */
  link: string;
  /** Optional summary/dek (rendered inside the <description>). */
  description?: string | null;
  /** Publish date; rendered as RFC-1123 (<pubDate>). */
  pubDate?: string | Date | null;
  categories?: string[];
  /** Absolute URL of an image (becomes an <enclosure>). */
  image?: string | null;
};

export type FeedOptions = {
  title: string;
  description: string;
  /** Absolute URL of the channel's HTML page. */
  link: string;
  /** Absolute URL of this feed (atom:link rel="self"). */
  feedUrl: string;
  items: FeedItem[];
  language?: string;
};

export function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/** Wrap text in CDATA, splitting any literal "]]>" safely. */
function cdata(value: string): string {
  return `<![CDATA[${value.replace(/]]>/g, "]]]]><![CDATA[>")}]]>`;
}

function absUrl(maybe: string | null | undefined, fallback: string): string {
  if (!maybe) return fallback;
  if (/^https?:\/\//i.test(maybe)) return maybe;
  return `${SITE_URL}${maybe.startsWith("/") ? "" : "/"}${maybe}`;
}

export function buildRss(opts: FeedOptions): string {
  const now = new Date().toUTCString();
  const items = opts.items
    .map((item) => {
      const link = absUrl(item.link, SITE_URL);
      const parts = [
        `    <title>${escapeXml(item.title)}</title>`,
        `    <link>${escapeXml(link)}</link>`,
        `    <guid isPermaLink="true">${escapeXml(link)}</guid>`,
      ];
      if (item.pubDate) {
        const d = item.pubDate instanceof Date ? item.pubDate : new Date(item.pubDate);
        if (!isNaN(d.getTime())) parts.push(`    <pubDate>${d.toUTCString()}</pubDate>`);
      }
      if (item.description) {
        parts.push(`    <description>${cdata(item.description.trim())}</description>`);
      }
      for (const c of item.categories ?? []) {
        if (c) parts.push(`    <category>${escapeXml(c)}</category>`);
      }
      if (item.image) {
        parts.push(
          `    <enclosure url="${escapeXml(absUrl(item.image, ""))}" type="image/png" length="0" />`,
        );
      }
      return `  <item>\n${parts.join("\n")}\n  </item>`;
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
  <title>${escapeXml(opts.title)}</title>
  <link>${escapeXml(absUrl(opts.link, SITE_URL))}</link>
  <description>${escapeXml(opts.description)}</description>
  <language>${escapeXml(opts.language ?? "en-us")}</language>
  <lastBuildDate>${now}</lastBuildDate>
  <generator>Earl Knows Ball</generator>
  <atom:link href="${escapeXml(absUrl(opts.feedUrl, SITE_URL))}" rel="self" type="application/rss+xml" />
${items}
</channel>
</rss>
`;
}

export type BackendFeedItem = {
  sport: string;
  kind: "articles" | "previews";
  title: string;
  path: string;
  summary: string | null;
  published_at: string | null;
  image: string | null;
  categories: string[];
  author: string | null;
};

/** Fetch feed items from the backend. Returns [] on any failure (never throw). */
export async function fetchFeedItems(
  backendBase: string,
  params: { sport?: string; kind?: string; limit?: number },
): Promise<BackendFeedItem[]> {
  const qs = new URLSearchParams({
    sport: params.sport ?? "all",
    kind: params.kind ?? "articles",
    limit: String(params.limit ?? 50),
  });
  try {
    const res = await fetch(`${backendBase}/seo/feed-data?${qs.toString()}`, {
      next: { revalidate: 600 },
    });
    if (!res.ok) return [];
    const data = (await res.json()) as { items?: BackendFeedItem[] };
    return data.items ?? [];
  } catch {
    return [];
  }
}

/** Map backend items to absolute-URL feed items. */
export function toFeedItems(items: BackendFeedItem[]): FeedItem[] {
  return items.map((it) => ({
    title: it.title,
    link: it.path,
    description: it.summary,
    pubDate: it.published_at,
    categories: it.categories,
    image: it.image,
  }));
}
